import Navbar from "./navbar";
import Head from "next/head";
import Footer from "./footer";
// import Navbar from "../components/Navbar";
function Layout({children} : { children:any }) {
    return (
		<div>
			<Head>
				<title>Navigation using nextjs and tailwindcss</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
            <main>{children}</main>
            <Footer />
        </div>
    );
}

export default Layout